# Generated by Django 4.2.1 on 2023-05-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='categoryName',
            field=models.CharField(max_length=100),
        ),
    ]
